spring:
  config:
    activate:
      on-profile: render
  #Configuracion del datasource para producción con H2
  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #Configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  #Inicialización de datos
  sql:
    init:
      mode: always
      continue-on-error: true

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

#Configurar el servidor embebido (Tomcat)
server:
  port: 8080

