spring:
  #Configuracion del datasource
  datasource:
    url: jdbc:mysql://localhost:3306/Hoteleria_Espe?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true

#Configurar el servidor embebido (Tomcat)
server:
  port: 8081